# Generated by Django 4.1.3 on 2022-12-03 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_meals_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='number',
            field=models.IntegerField(null=1),
            preserve_default=1,
        ),
    ]
