# Generated by Django 4.1.3 on 2023-02-07 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_category_image_remove_category_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('quantity', models.IntegerField(null=1)),
                ('price', models.FloatField(null=1)),
                ('image', models.ImageField(blank=1, upload_to='resturant')),
            ],
        ),
        migrations.RenameModel(
            old_name='Meals',
            new_name='Meal',
        ),
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
    ]
