# Generated by Django 4.1.3 on 2023-02-15 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_checkout_rename_meals_meal_rename_orders_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Checkout',
        ),
        migrations.AddField(
            model_name='order',
            name='order',
            field=models.TextField(null=1),
            preserve_default=1,
        ),
    ]
