# Generated by Django 4.1.3 on 2023-02-19 18:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.BigIntegerField(null=1, validators=[django.core.validators.MinLengthValidator(13)]),
        ),
    ]
