# Generated by Django 4.1.7 on 2023-04-22 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_meal_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='category',
            field=models.ForeignKey(default='brost', on_delete=django.db.models.deletion.CASCADE, to='api.category'),
        ),
    ]
