# Generated by Django 4.1.7 on 2023-04-22 06:57

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_meal_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='resturant'),
        ),
    ]
